In [3]:
from sklearn import svm,datasets
iris=datasets.load_iris()

In [13]:
import pandas as pd
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df['flower']=iris.target

#Star code below
df['flower']=df['flower'].apply(lambda x: iris.target_names[x])
df.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(iris.data, iris.target, test_size=0.2)

In [15]:
model=svm.SVC(kernel='rbf', C=30, gamma='auto')

In [16]:
model.fit(X_train,y_train)

SVC(C=30, gamma='auto')

In [17]:
model.score(X_test,y_test)

0.9333333333333333

In [20]:
from sklearn.model_selection import cross_val_score

In [21]:
cross_val_score(svm.SVC(kernel='linear', C=10, gamma='auto'),iris.data, iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [22]:
cross_val_score(svm.SVC(kernel='rbf', C=10, gamma='auto'),iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [23]:
cross_val_score(svm.SVC(kernel='rbf', C=20, gamma='auto'),iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [33]:
#here is a method that will take all these parameters and put them in a for loop for your convenience

In [35]:
#but this can be avoided by using the GridSearchCV function to directly compute these values for you

In [36]:
import numpy as np
kernels=['rbf', 'linear']
C=[1,10,20]
avg_scores={}
for kval in kernels:
    for cval in C:
        cv_scores=cross_val_score(svm.SVC(kernel=kval, C=cval, gamma='auto'),iris.data, iris.target, cv=5)
        avg_scores[kval+ '_ ' + str(cval)] = np.average(cv_scores)

In [37]:
avg_scores

{'rbf_ 1': 0.9800000000000001,
 'rbf_ 10': 0.9800000000000001,
 'rbf_ 20': 0.9666666666666668,
 'linear_ 1': 0.9800000000000001,
 'linear_ 10': 0.9733333333333334,
 'linear_ 20': 0.9666666666666666}

In [38]:
#here we are going to see the GridSearchCV function


In [39]:
from sklearn.model_selection import GridSearchCV

In [41]:
clf= GridSearchCV(svm.SVC(gamma='auto'),{
    'C': [1,10,20],
    'kernel': ['rbf', 'linear']
    
},
cv=5, return_train_score=False)

In [42]:
clf.fit(iris.data,iris.target)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear']})

In [43]:
 clf.cv_results_

{'mean_fit_time': array([0.00103421, 0.00156589, 0.00107079, 0.00062618, 0.00120983,
        0.00077186]),
 'std_fit_time': array([2.97594120e-04, 7.61507738e-04, 3.73629418e-04, 7.19077075e-05,
        2.03749655e-04, 1.54188714e-04]),
 'mean_score_time': array([0.00064578, 0.00076108, 0.00064201, 0.00052023, 0.00074368,
        0.00073075]),
 'std_score_time': array([0.00030347, 0.00033008, 0.00024081, 0.00020381, 0.0001955 ,
        0.00026709]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20

In [44]:
df=pd.DataFrame(clf.cv_results_)

In [45]:
df.head()

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001034      0.000298         0.000646        0.000303       1   
1       0.001566      0.000762         0.000761        0.000330       1   
2       0.001071      0.000374         0.000642        0.000241      10   
3       0.000626      0.000072         0.000520        0.000204      10   
4       0.001210      0.000204         0.000744        0.000195      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5

In [46]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_is_fitted',
 '_check_n_features',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'iid',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs',
 'n_splits_',
 'param_grid',
 'pre_

In [49]:
clf.best_score_

0.9800000000000001

In [51]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}